version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    - run:
        name: Run Tests
        command: npm run test

workflows:
  node-tests:
    jobs:
      - node/test
  build:
    jobs:
      - build