version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  test:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: test-results.xml
         
      - store_test_results:
          path: test-results.xml

workflows:
  version: 2
  test-and-heroku_deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          name: heroku/deploy-via-git
          requires: [test]
